# Heart Failure Readmission

In [2]:
import tensorflow as tf
print(tf.__version__)
tf.config.experimental.list_physical_devices('GPU')

2.1.0


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

## Data Preparation

In [16]:
import numpy as np
# Age (numeric), Diabetes (yes /no), Hypertension (yes/no), Hgba1c (numeric), Left vent ejection fraction (numerc)
fake_data_x = np.array([
    [77,1,1,10,25],
    [55,0,0,5,65],
    [56,1,1,7,45],
    [65,1,1,5.5,35],
    [56,0,1,6,55],
    [81,1,1,7,45]
])

# readmitted yes/no
fake_data_y = np.array([
    [1],
    [0],
    [1],
    [0],
    [0],
    [1]
])

In [17]:
print(fake_data_x.shape)
print(fake_data_y.shape)

(6, 5)
(6, 1)


## Data Preproccessing

In [18]:
# Normalization
print(fake_data_x)
for data in fake_data_x:
    data /= np.array([99.0,1.0,1.0,15.0,75])
print("")
print(fake_data_x)

[[77.   1.   1.  10.  25. ]
 [55.   0.   0.   5.  65. ]
 [56.   1.   1.   7.  45. ]
 [65.   1.   1.   5.5 35. ]
 [56.   0.   1.   6.  55. ]
 [81.   1.   1.   7.  45. ]]

[[0.77777778 1.         1.         0.66666667 0.33333333]
 [0.55555556 0.         0.         0.33333333 0.86666667]
 [0.56565657 1.         1.         0.46666667 0.6       ]
 [0.65656566 1.         1.         0.36666667 0.46666667]
 [0.56565657 0.         1.         0.4        0.73333333]
 [0.81818182 1.         1.         0.46666667 0.6       ]]


## Create Neural Network

In [21]:
model = tf.keras.models.Sequential([
    tf.keras.Input((5)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear')
])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                60        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 71
Trainable params: 71
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(optimizer='adam', loss="binary_crossentropy")

## Train the model on our data

In [38]:
model.fit(fake_data_x, fake_data_y, epochs=100)

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 743us/sample - loss: 0.8958
Epoch 2/100
6/6 [==============================] - 0s 279us/sample - loss: 0.8867
Epoch 3/100
6/6 [==============================] - 0s 284us/sample - loss: 0.8783
Epoch 4/100
6/6 [==============================] - 0s 304us/sample - loss: 0.8705
Epoch 5/100
6/6 [==============================] - 0s 322us/sample - loss: 0.8632
Epoch 6/100
6/6 [==============================] - 0s 241us/sample - loss: 0.8564
Epoch 7/100
6/6 [==============================] - 0s 249us/sample - loss: 0.8500
Epoch 8/100
6/6 [==============================] - 0s 223us/sample - loss: 0.8440
Epoch 9/100
6/6 [==============================] - 0s 197us/sample - loss: 0.8383
Epoch 10/100
6/6 [==============================] - 0s 299us/sample - loss: 0.8329
Epoch 11/100
6/6 [==============================] - 0s 216us/sample - loss: 0.8278
Epoch 12/100
6/6 [==============================] - 0s 210us/sample - loss: 0

## Test the model

In [39]:
test_data_x = np.array([[89,1,1,10,25]], dtype=np.float64)
test_data_x[0] /= np.array([99.0,1.0,1.0,15.0,75])
print(model.predict(test_data_x))

[[0.6144898]]
